import streamlit as st
import math
import calendar

# List of 72 angels with names and attributes
angels = [
    {"name": "Vehuiah", "attributes": "🌟💪 Vehuiah, known as 'God the Exalter,' symbolizes divine will and profound transformation, guiding individuals toward their destiny by supplying boundless energy during times of need and aiding in new beginnings with unwavering willpower. This angel is a patron of the liberal arts and sciences, elevating one's status and ranking in intellectual pursuits while offering wisdom and guidance for the Great Work—spiritual alchemy and personal evolution. Enthusiastic for science and the arts, Vehuiah empowers the accomplishment of the most difficult tasks, resolving conflicts through insightful strife management and fostering leadership with innovative thinking. Invoked for clarity amid challenges, it supports personal growth, helping navigate obstacles with a visionary approach. Associated with the Sephira Keter (Crown), the element of Fire 🔥, and the Ace of Wands in Tarot (upright), under Mars' rulership and Metatron's oversight. Invocation method: Recite the 3rd verse of Psalm 3—'But thou, O Lord, art a shield for me; my glory, and the lifter up of mine head' (Et tu Domine susceptor meus et gloria mea et exaltans caput meum)—during rituals involving fire for leadership and advancement. Those born under its influence are blessed with resilience, intellectual elevation, and the ability to turn strife into triumph, making Vehuiah a powerful ally for ambitious souls seeking enlightenment and success."},
    {"name": "Jeliel", "attributes": "❤️🕊️ Jeliel, meaning 'God Listening in Secret' or 'Strength,' provides love and wisdom in all forms, spreading harmony in relationships and aiding reconciliation during conflicts. This angel quells popular uprisings and secures victory over unjust attacks, embodying artful diplomacy, political acumen, and a champion's spirit for social justice. With a sprightly, outgoing, optimistic, energetic, and friendly nature, Jeliel ignites passion for meaningful connections, including romantic and sexual pursuits, while fostering emotional balance and inner peace. Invoked for mental clarity during emotional turmoil, it helps maintain grace under pressure and promotes fidelity in partnerships. Associated with the Sephira Keter, Fire element 🔥, and Ace of Wands Reversed in Tarot, under Mars' rulership and Metatron's guidance. Invocation method: Use the 19th verse of Psalm 22—'But be thou not far from me, O Lord: O my strength, haste thee to help me' (Tu autem Domine ne elongaveris auxilium tuum a me ad defensionem meam conspice)—in peace-making rituals. Individuals under Jeliel's influence experience profound calm, resilience, and success in social endeavors, making it ideal for those seeking harmonious relationships and triumphant resolutions."},
    {"name": "Sitael", "attributes": "🛡️🏰 Sitael, called 'Refuge, Fortress, and Confidence' or 'God, Hope of All Creatures,' helps achieve success and fulfill dreams by offering robust protection against adversities, weapons, and wild beasts, while defending against obstacles in life's path. This angel loves truth, keeps promises, and obliges those in need, promoting construction of strong foundations and resilience in challenging times. With merciful and compassionate virtues, Sitael rushes to aid the vulnerable, influencing valor and courage to establish truthful, lasting structures in personal and professional realms. Invoked for safeguarding and revealing truths, it fosters integrity and perseverance. Associated with Chokhmah Sephira (Wisdom), Fire element 🔥, and Two of Wands Upright in Tarot, under Sun's rulership and Metatron's oversight. Invocation method: Recite the 2nd verse of Psalm 91—'I will say of the Lord, He is my refuge and my fortress: my God; in him will I trust' (Dicet Domino: susceptor meus es tu et refugium meum: Deus meus, sperabo in eum)—during protective rituals. Those born under Sitael benefit from fortitude, hope, and the ability to overcome harm, making it a guardian for builders and truth-seekers."},
    {"name": "Elemiah", "attributes": "🔍🛡️ Elemiah, meaning 'Hidden God' or 'Concealed, Strong,' reveals the right life path by building inner strength, resilience, and uncovering hidden talents during difficult transitions. This angel protects against mental troubles, identifies traitors, and governs voyages, especially sea travels, calming anxiety, stress, depression, and worry. Industrious, successful, and keen for adventure, Elemiah empowers emotional stabilization and physical safety in strenuous journeys, influencing valor and discernment. Invoked for courage and clarity in revealing truths, it supports personal transformation and shields against adversity. Associated with Chokhmah Sephira, Fire element 🔥, and Two of Wands Reversed in Tarot, under Sun's rulership and Metatron's guidance. Invocation method: Use the 4th verse of Psalm 6—'Return, O Lord, deliver my soul: oh save me for thy mercies’ sake' (Convertere Domine, et eripe animam meam: salvum me fac propter misericordiam tuam)—in travel or revelation rituals. Individuals under Elemiah's influence gain self-discovery, protection, and the strength to navigate life's hidden challenges with diligence and insight."},
    {"name": "Mahasiah", "attributes": "📚⚖️ Mahasiah, known as 'God the Savior' or 'Seeking Safety from Trouble,' guides students and promotes harmony, balance, and self-improvement by correcting past mistakes and encouraging the pursuit of higher education, spiritual enlightenment, and occult philosophy. This angel governs high sciences, theology, alchemy, and liberal arts, facilitating easy learning and honest pleasures while living in peace with everyone. With virtues of intellectual curiosity and peacemaking, Mahasiah turns challenges into opportunities, influencing prudence and wise decision-making. Invoked for healing, balance, and knowledge acquisition, it aligns personal aspirations with spiritual growth. Associated with Binah Sephira (Understanding), Fire element 🔥, and Three of Wands Upright in Tarot, under Jupiter's rulership. Invocation method: Recite the 5th verse of Psalm 34—'I sought the Lord, and he heard me, and delivered me from all my fears' (Exquisivi Dominum, et exaudivit me: et ex omnibus tribulationibus meis eripuit me)—in study or reconciliation rituals. Those born under Mahasiah are blessed with adaptability, wisdom, and a balanced life, making it ideal for scholars and harmony-seekers."},
    {"name": "Lelahel", "attributes": "🌿💡 Lelahel clears doubts and encourages introspection, promoting healing and vitality for overall well-being by illuminating the path to self-discovery and emotional clarity. This angel aids in dispelling confusion, fostering profound self-reflection, and enhancing physical and spiritual health through restorative energies. With virtues of enlightenment and renewal, Lelahel influences positive change and resilience in times of uncertainty. Invoked for health restoration and inner peace, it supports those seeking vitality and mental clarity. Associated with Aries influences and fire elements 🔥. No specific invocation psalm mentioned in sources, but meditate on its name for healing rituals. Individuals under Lelahel's guidance experience rejuvenation, introspection, and a renewed sense of purpose, making it a healer for body and soul."},
    {"name": "Achaiah", "attributes": "⏳🔮 Achaiah, 'God Who Gives Joy,' grants sacred patience in difficult times, encouraging persistence and determination for long-term goals by uncovering hidden truths and mastering perseverance. This angel inspires a deep understanding of life's mysteries, fostering calm insight and resilience in challenges. With virtues of revelation and endurance, Achaiah influences philosophical outlooks and steady progress. Invoked for joy and patience, it helps see the bigger picture. Associated with Taurus degrees and earth stability 🌍. Invocation: Psalm rituals for revelation. Born under Achaiah enjoy balanced, insightful lives, ideal for those pursuing enduring success."},
    {"name": "Cahetel", "attributes": "🌾🙏 Cahetel brings changes in life, attracts abundance and prosperity, and fosters gratitude by blessing harvests and material wealth while driving away evil spirits. This angel supports agricultural endeavors, divine blessings, and protection from negativity, influencing thankfulness and positive transformation. Invoked for abundance and banishing harm, it aids in life's shifts. Associated with Taurus and earth elements 🌍. Invocation: Psalms for blessings. Individuals under Cahetel experience prosperity and spiritual protection, making it a provider for grateful hearts."},
    {"name": "Haziel", "attributes": "🤝💖 Haziel brings forgiveness and reconciliation, offers mercy and compassion for healing emotional wounds by promoting divine friendship and unconditional love. This angel aids in mending relationships, influencing kindness and emotional recovery. Invoked for mercy and harmony. Associated with universal love. Invocation: Meditation on forgiveness. Born under Haziel are compassionate healers."},
    {"name": "Aladiah", "attributes": "🔄🌟 Aladiah, bearer of second chances with healing ability, protects from negative influences and purifies spiritually by offering grace and renewal after errors. This angel supports recovery from illness and moral regeneration, influencing divine grace. Invoked for healing and protection. Associated with purity. Invocation: Psalms for redemption. Ideal for those seeking fresh starts."},
    {"name": "Lauviah", "attributes": "🧠🔮 Lauviah enhances intuition in earthly and spiritual realms, inspires revelation and intuitive wisdom by aiding prophetic dreams and higher understanding. This angel combats insomnia and anxiety, influencing fame through talents. Invoked for intuition. Associated with night visions. Invocation: Night meditations. Born under Lauviah are intuitive visionaries."},
    {"name": "Hahaiah", "attributes": "❤️🛡️ Hahaiah teaches self-love and meditation, provides refuge and comfort in distress by protecting from adversity and revealing hidden truths. This angel influences discretion and wisdom. Invoked for shelter. Associated with inner peace. Invocation: Meditative prayers. Ideal for self-care seekers."},
    {"name": "Iezalel", "attributes": "👫🤝 Iezalel brings reconciliation in relationships, fosters loyalty and fidelity in friendships by repairing broken bonds and enhancing memory. This angel influences unity and harmony. Invoked for loyalty. Associated with partnerships. Invocation: Relationship rituals. Born under Iezalel are loyal companions."},
    {"name": "Mebahel", "attributes": "⚖️🗽 Mebahel, protector of truth, justice, freedom, and commitment, aids in liberation from oppression by defending the innocent and abolishing slavery. This angel influences legal victories. Invoked for justice. Associated with truth. Invocation: Psalms for freedom. Ideal for activists."},
    {"name": "Hariel", "attributes": "🧹🌱 Hariel helps rid addictions and dependencies, promotes purification and spiritual growth by aiding scientific discoveries and religious sentiments. This angel influences purity and faith. Invoked for cleansing. Associated with renewal. Invocation: Purification rituals. Born under Hariel are pure innovators."},
    {"name": "Hakamiah", "attributes": "👑🤝 Hakamiah teaches loyalty according to divine principles, guards against betrayal and fosters peace by crowning the deserving and protecting from traitors. This angel influences nobility and frankness. Invoked for loyalty. Associated with crown. Invocation: Loyalty oaths. Ideal for leaders."},
    {"name": "Lauviah", "attributes": "🏆💪 Lauviah, angel of victory and successful people, aids in overcoming challenges and manifesting desires by granting fame to artists and protection from storms. This angel influences triumph and sleep. Invoked for success. Associated with victory. Invocation: Victory chants. Born under Lauviah are winners."},
    {"name": "Caliel", "attributes": "⚖️👁️ Caliel helps understand good vs. evil, promotes justice and moral integrity by revealing truth in trials and confounding the guilty. This angel influences divine justice. Invoked for clarity. Associated with truth. Invocation: Justice prayers. Ideal for judges."},
    {"name": "Leuviah", "attributes": "🧠📜 Leuviah saves memories of past lives, enhances memory and learning abilities by granting intelligence and joviality. This angel influences forgiveness and patience. Invoked for memory. Associated with past. Invocation: Memory meditations. Born under Leuviah are wise rememberers."},
    {"name": "Pahaliah", "attributes": "🔄🙏 Pahaliah helps rid old bad behaviors, aids spiritual growth and divine wisdom by discerning truth and promoting virtue. This angel influences theology and morality. Invoked for redemption. Associated with virtue. Invocation: Conversion rituals. Ideal for seekers of truth."},
    {"name": "Nelchael", "attributes": "📚🛡️ Nelchael, for those desiring to learn, helps with knowledge and dispelling ignorance by conquering calumniators and loving mathematics. This angel influences sciences and arts. Invoked for learning. Associated with knowledge. Invocation: Study psalms. Born under Nelchael are eager scholars."},
    {"name": "Yeiaiel", "attributes": "📏⭐ Yeiaiel brings sense of order and discipline, aids fame, fortune, and accomplishment by protecting commerce and travel. This angel influences diplomacy and voyages. Invoked for order. Associated with fortune. Invocation: Travel prayers. Ideal for entrepreneurs."},
    {"name": "Melahel", "attributes": "🌿👩‍⚕️ Melahel heals and protects healers, promotes vitality and protection during travel by curing diseases and aiding in plant knowledge. This angel influences nature and courage. Invoked for healing. Associated with herbs. Invocation: Healing rituals. Born under Melahel are natural healers."},
    {"name": "Hahuiah", "attributes": "🗣️🔍 Hahuiah grants sincerity and truth, helps discernment and defending integrity by protecting exiles and granting grace. This angel influences amnesty. Invoked for truth. Associated with sincerity. Invocation: Truth psalms. Ideal for honest souls."},
    {"name": "Nithaiah", "attributes": "📖✨ Nithaiah provides wisdom and spiritual understanding, aids access to hidden truths and mysticism by revealing mysteries through dreams. This angel influences occult sciences. Invoked for wisdom. Associated with magic. Invocation: Dream rituals. Born under Nithaiah are mystics."},
    {"name": "Haaiah", "attributes": "🤝🕊️ Haaiah promotes diplomacy and conflict resolution, fosters peace and cooperation by aiding ambassadors and protecting secrets. This angel influences political science. Invoked for peace. Associated with discretion. Invocation: Diplomacy prayers. Ideal for negotiators."},
    {"name": "Yeratel", "attributes": "🔄🌟 Yeratel aids transformation and positive change, supports personal growth by confounding enemies and propagating light. This angel influences civilization and liberty. Invoked for change. Associated with light. Invocation: Transformation rites. Born under Yeratel are reformers."},
    {"name": "Seheiah", "attributes": "🛡️🩹 Seheiah offers protection and longevity, wards off illness and adversity by foreseeing dangers and aiding recovery. This angel influences health and prudence. Invoked for protection. Associated with longevity. Invocation: Health psalms. Ideal for guardians of health."},
    {"name": "Reiyel", "attributes": "📣🌟 Reiyel provides divine inspiration and guidance, aids enlightenment by liberating from enemies and promoting religious sentiment. This angel influences meditation. Invoked for inspiration. Associated with liberation. Invocation: Enlightenment meditations. Born under Reiyel are inspired leaders."},
    {"name": "Omael", "attributes": "⏳🌱 Omael promotes patience and fertility, nurtures growth and abundance by multiplying species and confounding despair. This angel influences chemistry and physicians. Invoked for fertility. Associated with multiplication. Invocation: Growth rituals. Ideal for creators."},
    {"name": "Lecabel", "attributes": "🧠🎨 Lecabel enhances intelligence and creativity, aids problem-solving and innovation by inspiring artists and administrators. This angel influences vegetation and astronomy. Invoked for ideas. Associated with talent. Invocation: Creative prayers. Born under Lecabel are innovators."},
    {"name": "Vasariah", "attributes": "⚖️❤️ Vasariah supports justice and forgiveness, promotes balance and harmony by aiding judges and eloquent speakers. This angel influences memory and generosity. Invoked for clemency. Associated with justice. Invocation: Forgiveness psalms. Ideal for mediators."},
    {"name": "Yehuiah", "attributes": "🙏👑 Yehuiah aids obedience and loyalty, helps discern divine will by protecting princes and confounding conspiracies. This angel influences subordination. Invoked for loyalty. Associated with hierarchy. Invocation: Obedience rituals. Born under Yehuiah are devoted followers."},
    {"name": "Lehahiah", "attributes": "📏🏗️ Lehahiah promotes order and stability, helps with focus and long-term goals by calming wrath and gaining favor from superiors. This angel influences faithful service. Invoked for order. Associated with peace. Invocation: Stability prayers. Ideal for organizers."},
    {"name": "Chavakiah", "attributes": "🤝💔 Chavakiah aids reconciliation and healing relationships by maintaining harmony in families and aiding inheritances. This angel influences amicable divisions. Invoked for harmony. Associated with family. Invocation: Reconciliation rites. Born under Chavakiah are peacemakers."},
    {"name": "Menadel", "attributes": "💼📈 Menadel supports work and productivity, helps find purpose and career advancement by preserving employment and aiding exiles. This angel influences inner conviction. Invoked for work. Associated with labor. Invocation: Career psalms. Ideal for professionals."},
    {"name": "Aniel", "attributes": "💥🧠 Aniel aids spiritual breakthroughs and inner strength, overcomes challenges by inspiring scientists and breaking old habits. This angel influences meditation. Invoked for breakthroughs. Associated with virtue. Invocation: Strength meditations. Born under Aniel are breakthrough achievers."},
    {"name": "Haamiah", "attributes": "🕯️🙏 Haamiah supports ritual and spiritual practice, connects with divine energies by preparing for ceremonies and protecting from error. This angel influences religious cults. Invoked for rituals. Associated with truth. Invocation: Ceremony prayers. Ideal for practitioners."},
    {"name": "Rehael", "attributes": "🩹👨‍👩‍👧 Rehael promotes healing and familial love, fosters harmony in family by curing diseases and inspiring filial respect. This angel influences health and longevity. Invoked for healing. Associated with paternity. Invocation: Family rituals. Born under Rehael are healers."},
    {"name": "Ieiazel", "attributes": "🗽🔓 Ieiazel aids liberation from oppression, breaks negative patterns by consoling prisoners and aiding writers. This angel influences printing and libraries. Invoked for liberation. Associated with comfort. Invocation: Freedom psalms. Ideal for liberators."},
    {"name": "Hahahel", "attributes": "🙏🔥 Hahahel inspires faith and devotion, supports spiritual service by confounding enemies of religion and aiding missionaries. This angel influences clergy. Invoked for faith. Associated with virtue. Invocation: Devotion prayers. Born under Hahahel are faithful servants."},
    {"name": "Mikael", "attributes": "👑📜 Mikael aids in politics and leadership, maintains order and collective goals by overseeing voyages and inspiring diplomats. This angel influences teachers of politics. Invoked for order. Associated with vision. Invocation: Leadership rituals. Ideal for leaders."},
    {"name": "Veualiah", "attributes": "💰🏆 Veualiah brings prosperity and success in endeavors, manifests wealth by destroying enemies and exalting through victory. This angel influences peace and commerce. Invoked for prosperity. Associated with military. Invocation: Success psalms. Born under Veualiah are prosperous warriors."},
    {"name": "Yelahiah", "attributes": "💪🛡️ Yelahiah provides valor and courage, offers protection in conflicts by ensuring success in useful enterprises and protecting magistrates. This angel influences warriors. Invoked for courage. Associated with virtue. Invocation: Valor prayers. Ideal for brave souls."},
    {"name": "Sealiah", "attributes": "🔥💥 Sealiah motivates enthusiasm and awakening passion, overcomes inertia by confounding the proud and restoring health. This angel influences vegetation and fire. Invoked for motivation. Associated with movement. Invocation: Enthusiasm rituals. Born under Sealiah are passionate movers."},
    {"name": "Ariel", "attributes": "🔮📖 Ariel enhances revelation and psychic abilities, uncovers hidden truths by aiding discoveries and perceptive dreams. This angel influences nocturnal visions. Invoked for revelation. Associated with perception. Invocation: Dream meditations. Ideal for psychics."},
    {"name": "Asaliah", "attributes": "🧘‍♂️🔍 Asaliah promotes contemplation and divine understanding, provides clarity by elevating souls to see God's works. This angel influences physics and truth. Invoked for contemplation. Associated with elevation. Invocation: Contemplative prayers. Born under Asaliah are contemplative sages."},
    {"name": "Mihael", "attributes": "🌹👫 Mihael supports fertility and marital harmony, fosters loving relationships by preserving peace and union between spouses. This angel influences fidelity. Invoked for harmony. Associated with generation. Invocation: Love rituals. Ideal for couples."},
    {"name": "Vehuel", "attributes": "🌟🤲 Vehuel inspires elevation and generosity, promotes noble actions by exalting toward greatness and confounding flatterers. This angel influences sensitivity. Invoked for elevation. Associated with greatness. Invocation: Generosity psalms. Born under Vehuel are noble givers."},
    {"name": "Daniel", "attributes": "🗣️⚖️ Daniel aids eloquence and decision-making, promotes mercy and wise judgment by consoling in adversity and influencing lawyers. This angel influences sympathy. Invoked for eloquence. Associated with mercy. Invocation: Decision prayers. Ideal for speakers."},
    {"name": "Hahasiah", "attributes": "🩺🔬 Hahasiah promotes healing and medicine, supports physical and alchemical knowledge by revealing secrets of nature and elevating souls. This angel influences chemistry. Invoked for healing. Associated with stone of wise. Invocation: Healing rituals. Born under Hahasiah are healers and alchemists."},
    {"name": "Imamiah", "attributes": "🔄❤️ Imamiah aids expiation and forgiveness, encourages self-reflection and redemption by destroying enemies and humbling the proud. This angel influences vigor. Invoked for forgiveness. Associated with journeys. Invocation: Redemption psalms. Ideal for redeemers."},
    {"name": "Nanael", "attributes": "🧘‍♀️📚 Nanael supports spiritual communication and meditation, aids connection to higher knowledge by inspiring high sciences and influencing ecclesiastics. This angel influences abstraction. Invoked for communication. Associated with solitude. Invocation: Meditation rituals. Born under Nanael are spiritual scholars."},
    {"name": "Nithael", "attributes": "🛡️👑 Nithael provides stability and legitimacy, helps maintain health and positions by preserving kings and empires. This angel influences renown. Invoked for stability. Associated with beauty. Invocation: Stability prayers. Ideal for rulers."},
    {"name": "Mebahiah", "attributes": "🧠🕊️ Mebahiah aids intellectual lucidity and moral integrity by contemplating divine ideas and inspiring religion. This angel influences morality. Invoked for lucidity. Associated with consolation. Invocation: Moral rituals. Born under Mebahiah are moral thinkers."},
    {"name": "Poyel", "attributes": "🍀🤗 Poyel brings fortune and support with modesty and humility by granting health, wealth, and philosophical talents. This angel influences fame. Invoked for fortune. Associated with moderation. Invocation: Humility psalms. Ideal for modest achievers."},
    {"name": "Nemamiah", "attributes": "🔍💼 Nemamiah reveals deep personal problems, provides discernment, leadership, and prosperity by aiding generals and freeing prisoners. This angel influences prosperity. Invoked for discernment. Associated with labor. Invocation: Leadership prayers. Born under Nemamiah are discerning leaders."},
    {"name": "Yeialel", "attributes": "🔮🧠 Yeialel develops psychic abilities like clairvoyance, combats sorrow for mental clarity by consoling and healing eye diseases. This angel influences commerce. Invoked for clairvoyance. Associated with fortitude. Invocation: Psychic rituals. Ideal for seers."},
    {"name": "Harahel", "attributes": "🌟💭 Harahel helps make dreams come true with positive energy, aiding intellectual pursuits and protecting from sterility. This angel influences treasures. Invoked for fertility. Associated with children. Invocation: Dream fulfillment prayers. Born under Harahel are fertile minds."},
    {"name": "Mitzrael", "attributes": "🔧⚖️ Mitzrael corrects mistakes, guides to understand authority by curing mental ills and inspiring loyalty. This angel influences virtue. Invoked for correction. Associated with reparation. Invocation: Authority psalms. Ideal for teachers."},
    {"name": "Umabel", "attributes": "🔍🌍 Umabel provides deep awareness of life, concentration by aiding friendships and affinity with astronomy. This angel influences physicists. Invoked for awareness. Associated with analogy. Invocation: Friendship rituals. Born under Umabel are aware friends."},
    {"name": "Iahhel", "attributes": "☀️🧘 Iahhel boosts positive thoughts, teaches enjoyment of solitude and tranquility by acquiring wisdom and aiding retirement. This angel influences philosophers. Invoked for positivity. Associated with knowledge. Invocation: Solitude meditations. Ideal for philosophers."},
    {"name": "Anauel", "attributes": "📞🤝 Anauel ensures successful communication and relationships by protecting commerce and uniting spirits. This angel influences cashiers. Invoked for communication. Associated with unity. Invocation: Relationship prayers. Born under Anauel are communicators."},
    {"name": "Mehiel", "attributes": "🧠🛡️ Mehiel favors imagination, intelligence, protects against dark energies by inspiring writers and aiding against rabies. This angel influences printing. Invoked for imagination. Associated with literature. Invocation: Creative psalms. Ideal for creators."},
    {"name": "Damabiah", "attributes": "❤️🔄 Damabiah gives unconditional love, supports transformation by aiding naval enterprises and protecting from shipwrecks. This angel influences seas. Invoked for love. Associated with wisdom. Invocation: Love rituals. Born under Damabiah are loving transformers."},
    {"name": "Manakel", "attributes": "😨🔍 Manakel eliminates fears through understanding, aids emotional stability by calming nightmares and aiding vegetation. This angel influences sleep. Invoked for stability. Associated with goodness. Invocation: Fear-banishing prayers. Ideal for peaceful sleepers."},
    {"name": "Eiael", "attributes": "🧭💪 Eiael guides good decisions, supports when all seems lost, enhances learning by consoling in adversity and aiding occult sciences. This angel influences truth. Invoked for guidance. Associated with commerce. Invocation: Decision rituals. Born under Eiael are resilient learners."},
    {"name": "Habuhiah", "attributes": "🩹🌿 Habuhiah patterns for medical and spiritual treatments, promotes vitality and health by curing diseases and aiding agriculture. This angel influences fertility. Invoked for health. Associated with harvest. Invocation: Healing psalms. Ideal for healers."},
    {"name": "Rochel", "attributes": "⚖️🏆 Rochel gives what is deserved, symbolizes justice and equity by restoring lost goods and aiding fame. This angel influences renown. Invoked for justice. Associated with rights. Invocation: Equity prayers. Born under Rochel are just victors."},
    {"name": "Jabamiah", "attributes": "🌟🩹 Jabamiah delivers healing energy, regenerates and restores harmony by governing phenomena and aiding philosophy. This angel influences creation. Invoked for healing. Associated with alchemy. Invocation: Regeneration rituals. Ideal for regenerators."},
    {"name": "Haiaiel", "attributes": "🛡️⚖️ Haiaiel provides divine protection, helps make just decisions by confounding traitors and delivering the oppressed. This angel influences courage. Invoked for protection. Associated with weapons. Invocation: Protection psalms. Born under Haiaiel are protected deciders."},
    {"name": "Mumiah", "attributes": "🔄⚡ Mumiah helps complete tasks, gives energy for new beginnings, revitalizes by bringing success to experiments and aiding medicine. This angel influences chemistry. Invoked for completion. Associated with disclosure. Invocation: Completion rituals. Ideal for finishers."}
]

st.title("Guardian Angel Calculator")

st.markdown("""
### How it works
This app determines your guardian angel based on your birth date using Kabbalistic tradition. It calculates the sun's apparent ecliptic longitude at noon on your birth date and maps it to one of 72 angels (each governing 5 degrees of the zodiac circle, starting from the vernal equinox). This method provides accuracy for leap years and dates between 1900 and 2100, using astronomical formulas aligned with traditional references, including considerations for historical figures like Jesus (traditional birth December 25 corresponding to Poyel in approximate fixed ranges, but calculated precisely). The year is used to handle leap years correctly, and February 29 is valid only in leap years.
""")

# Input birth date
birth_date = st.date_input("Enter your birth date", min_value=datetime(1900, 1, 1), max_value=datetime(2100, 12, 31))

if st.button("Find My Guardian Angel"):
    if birth_date:
        year = birth_date.year
        month = birth_date.month
        day = birth_date.day

        if month == 2 and day == 29 and not calendar.isleap(year):
            st.error("February 29 is not valid for non-leap years. Please select a valid date.")
        else:
            # Calculate Julian Day at 0h UT
            if month <= 2:
                year -= 1
                month += 12
            a = year // 100
            b = a // 4
            c = 2 - a + b
            e = int(365.25 * (year + 4716))
            f = int(30.6001 * (month + 1))
            jd = c + day + e + f - 1524.5

            # Add 0.5 for noon UT
            jd += 0.5

            # Calculate n
            n = jd - 2451545.0

            # Mean anomaly g in degrees
            g = (357.529 + 0.98560028 * n) % 360
            g_rad = math.radians(g)

            # Mean longitude L in degrees
            l = (280.459 + 0.98564736 * n) % 360

            # Apparent ecliptic longitude lambda in degrees
            lambda_deg = (l + 1.915 * math.sin(g_rad) + 0.020 * math.sin(2 * g_rad)) % 360

            # Calculate index
            index = int(lambda_deg // 5)

            angel = angels[index]
            st.success(f"Your Guardian Angel is **{angel['name']}** (based on ecliptic longitude {lambda_deg:.2f}°)")
            st.write(angel['attributes'])
    else:
        st.warning("Please enter your birth date.")