import streamlit as st
import math
import calendar
from datetime import datetime

# List of 72 angels + 5 archangels with updated details
angels = [
    {"number": 1, "name": "Vehuiah", "zodiac": "Aries", "element": "Fire", "attributes": "🌟💪 Vehuiah, known as 'God the Exalter,' symbolizes divine will and profound transformation, guiding individuals toward their destiny by supplying boundless energy during times of need and aiding in new beginnings with unwavering willpower. This angel is a patron of the liberal arts and sciences, elevating one's status and ranking in intellectual pursuits while offering wisdom and guidance for the Great Work—spiritual alchemy and personal evolution. Enthusiastic for science and the arts, Vehuiah empowers the accomplishment of the most difficult tasks, resolving conflicts through insightful strife management and fostering leadership with innovative thinking. Invoked for clarity amid challenges, it supports personal growth, helping navigate obstacles with a visionary approach. Associated with the Sephira Keter (Crown), the element of Fire 🔥, and the Ace of Wands in Tarot (upright), under Mars' rulership and Metatron's oversight. Invocation method: Recite the 3rd verse of Psalm 3—'But thou, O Lord, art a shield for me; my glory, and the lifter up of mine head' (Et tu Domine susceptor meus et gloria mea et exaltans caput meum)—during rituals involving fire for leadership and advancement. Those born under its influence are blessed with resilience, intellectual elevation, and the ability to turn strife into triumph, making Vehuiah a powerful ally for ambitious souls seeking enlightenment and success. Sparks new beginnings and helps individuals overcome challenges. Supports the undertaking of the Great Work; known for wisdom; patron for liberal arts and sciences. Elevates ranking and status.", "psalm": "3:3", "sigil_desc": "Features a six-pointed star with the divine name Vehu repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Vehuiah formed by a single anti-clockwise ring of letters, including the suffix iah added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 2, "name": "Jeliel", "zodiac": "Aries", "element": "Fire", "attributes": "❤️🕊️ Jeliel, meaning 'God Listening in Secret' or 'Strength,' provides love and wisdom in all forms, spreading harmony in relationships and aiding reconciliation during conflicts. This angel quells popular uprisings and secures victory over unjust attacks, embodying artful diplomacy, political acumen, and a champion's spirit for social justice. With a sprightly, outgoing, optimistic, energetic, and friendly nature, Jeliel ignites passion for meaningful connections, including romantic and sexual pursuits, while fostering emotional balance and inner peace. Invoked for mental clarity during emotional turmoil, it helps maintain grace under pressure and promotes fidelity in partnerships. Associated with the Sephira Keter, Fire element 🔥, and Ace of Wands Reversed in Tarot, under Mars' rulership and Metatron's guidance. Invocation method: Use the 19th verse of Psalm 22—'But be thou not far from me, O Lord: O my strength, haste thee to help me' (Tu autem Domine ne elongaveris auxilium tuum a me ad defensionem meam conspice)—in peace-making rituals. Individuals under Jeliel's influence experience profound calm, resilience, and success in social endeavors, making it ideal for those seeking harmonious relationships and triumphant resolutions. Promotes love, loyalty, and fidelity in relationships. Invoke to embody artful diplomacy and political acumen; facilitates victory; champion of social justice; sprightly, outgoing, optimistic, energetic, and friendly.", "psalm": "22:19", "sigil_desc": "Features a six-pointed star with the divine name Yeli repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Jeliel formed by a single anti-clockwise ring of letters, including the suffix el added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 3, "name": "Sitael", "zodiac": "Aries", "element": "Fire", "attributes": "🛡️🏰 Sitael, called 'Refuge, Fortress, and Confidence' or 'God, Hope of All Creatures,' helps achieve success and fulfill dreams by offering robust protection against adversities, weapons, and wild beasts, while defending against obstacles in life's path. This angel loves truth, keeps promises, and obliges those in need, promoting construction of strong foundations and resilience in challenging times. With merciful and compassionate virtues, Sitael rushes to aid the vulnerable, influencing valor and courage to establish truthful, lasting structures in personal and professional realms. Invoked for safeguarding and revealing truths, it fosters integrity and perseverance. Associated with Chokhmah Sephira (Wisdom), Fire element 🔥, and Two of Wands Upright in Tarot, under Sun's rulership and Metatron's oversight. Invocation method: Recite the 2nd verse of Psalm 91—'I will say of the Lord, He is my refuge and my fortress: my God; in him will I trust' (Dicet Domino: susceptor meus es tu et refugium meum: Deus meus, sperabo in eum)—during protective rituals. Those born under Sitael benefit from fortitude, hope, and the ability to overcome harm, making it a guardian for builders and truth-seekers. Protects against adversity and helps manifest goals. A protector. Defends against attacks. Reveals truths. Merciful and compassionate, aids those in need of protection.", "psalm": "91:2", "sigil_desc": "Features a six-pointed star with the divine name Sit repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Sitael formed by a single anti-clockwise ring of letters, including the suffix el added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 4, "name": "Elemiah", "zodiac": "Aries", "element": "Fire", "attributes": "🔍🛡️ Elemiah, meaning 'Hidden God' or 'Concealed, Strong,' reveals the right life path by building inner strength, resilience, and uncovering hidden talents during difficult transitions. This angel protects against mental troubles, identifies traitors, and governs voyages, especially sea travels, calming anxiety, stress, depression, and worry. Industrious, successful, and keen for adventure, Elemiah empowers emotional stabilization and physical safety in strenuous journeys, influencing valor and discernment. Invoked for courage and clarity in revealing truths, it supports personal transformation and shields against adversity. Associated with Chokhmah Sephira, Fire element 🔥, and Two of Wands Reversed in Tarot, under Sun's rulership and Metatron's guidance. Invocation method: Use the 4th verse of Psalm 6—'Return, O Lord, deliver my soul: oh save me for thy mercies’ sake' (Convertere Domine, et eripe animam meam: salvum me fac propter misericordiam tuam)—in travel or revelation rituals. Individuals under Elemiah's influence gain self-discovery, protection, and the strength to navigate life's hidden challenges with diligence and insight. Encourages career success and helps recover from betrayal. Calms anxiety, stress, depression, and worry. Travel protection, especially by sea or over long distances. Guardian during strenuous voyages. Hard-working, diligent, productive, and conscientious.", "psalm": "6:4", "sigil_desc": "Features a six-pointed star with the divine name Elem repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Elemiah formed by a single anti-clockwise ring of letters, including the suffix iah added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 5, "name": "Mahasiah", "zodiac": "Aries", "element": "Fire", "attributes": "📚⚖️ Mahasiah, known as 'God the Savior' or 'Seeking Safety from Trouble,' guides students and promotes harmony, balance, and self-improvement by correcting past mistakes and encouraging the pursuit of higher education, spiritual enlightenment, and occult philosophy. This angel governs high sciences, theology, alchemy, and liberal arts, facilitating easy learning and honest pleasures while living in peace with everyone. With virtues of intellectual curiosity and peacemaking, Mahasiah turns challenges into opportunities, influencing prudence and wise decision-making. Invoked for healing, balance, and knowledge acquisition, it aligns personal aspirations with spiritual growth. Associated with Binah Sephira (Understanding), Fire element 🔥, and Three of Wands Upright in Tarot, under Jupiter's rulership. Invocation method: Recite the 5th verse of Psalm 34—'I sought the Lord, and he heard me, and delivered me from all my fears' (Exquisivi Dominum, et exaudivit me: et ex omnibus tribulationibus meis eripuit me)—in study or reconciliation rituals. Those born under Mahasiah are blessed with adaptability, wisdom, and a balanced life, making it ideal for scholars and harmony-seekers. Brings peace, harmony, and intellectual enlightenment. Patron of high sciences and occult philosophy. Facilitates learning in theology, alchemy, physics. An educator. Embraces quest for knowledge. Seeks peace, diffuses conflicts.", "psalm": "34:4", "sigil_desc": "Features a six-pointed star with the divine name Mahash repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Mahasiah formed by a single anti-clockwise ring of letters, including the suffix iah added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 6, "name": "Lelahel", "zodiac": "Aries", "element": "Fire", "attributes": "🌿💡 Lelahel clears doubts and encourages introspection, promoting healing and vitality for overall well-being by illuminating the path to self-discovery and emotional clarity. This angel aids in dispelling confusion, fostering profound self-reflection, and enhancing physical and spiritual health through restorative energies. With virtues of enlightenment and renewal, Lelahel influences positive change and resilience in times of uncertainty. Invoked for health restoration and inner peace, it supports those seeking vitality and mental clarity. Associated with Aries influences and fire elements 🔥. No specific invocation psalm mentioned in sources, but meditate on its name for healing rituals. Individuals under Lelahel's guidance experience rejuvenation, introspection, and a renewed sense of purpose, making it a healer for body and soul. Enhances healing and attracts prosperity. A healing angel. Patron of medical knowledge and science; seeks to cure illness and disease. Guards those on path for greater public recognition and material prosperity.", "psalm": "9:11", "sigil_desc": "Features a six-pointed star with the divine name Lelah repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Lelahel formed by a single anti-clockwise ring of letters, including the suffix el added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 7, "name": "Achaiah", "zodiac": "Taurus", "element": "Earth", "attributes": "⏳🔮 Achaiah, 'God Who Gives Joy,' grants sacred patience in difficult times, encouraging persistence and determination for long-term goals by uncovering hidden truths and mastering perseverance. This angel inspires a deep understanding of life's mysteries, fostering calm insight and resilience in challenges. With virtues of revelation and endurance, Achaiah influences philosophical outlooks and steady progress. Invoked for joy and patience, it helps see the bigger picture. Associated with Taurus degrees and earth stability 🌍. Invocation: Psalm rituals for revelation. Born under Achaiah enjoy balanced, insightful lives, ideal for those pursuing enduring success. Assists in patience and understanding life’s mysteries. Guardian and ally to those undertaking greatest challenges; guardian to those on hero’s journey. Can reveal secrets of nature to seekers.", "psalm": "103:8", "sigil_desc": "Features a six-pointed star with the divine name Acha repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Achaiah formed by a single anti-clockwise ring of letters, including the suffix iah added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 8, "name": "Cahetel", "zodiac": "Taurus", "element": "Earth", "attributes": "🌾🙏 Cahetel brings changes in life, attracts abundance and prosperity, and fosters gratitude by blessing harvests and material wealth while driving away evil spirits. This angel supports agricultural endeavors, divine blessings, and protection from negativity, influencing thankfulness and positive transformation. Invoked for abundance and banishing harm, it aids in life's shifts. Associated with Taurus and earth elements 🌍. Invocation: Psalms for blessings. Individuals under Cahetel experience prosperity and spiritual protection, making it a provider for grateful hearts. Encourages gratitude and brings blessings to households. Drives away evil spirits, demons, infectious diseases, and rot; protects agriculture, productivity, and harvests. Angel of deep reverence and faith.", "psalm": "95:6", "sigil_desc": "Features a six-pointed star with the divine name Cahet repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Cahetel formed by a single anti-clockwise ring of letters, including the suffix el added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 9, "name": "Haziel", "zodiac": "Taurus", "element": "Earth", "attributes": "🤝💖 Haziel brings forgiveness and reconciliation, offers mercy and compassion for healing emotional wounds by promoting divine friendship and unconditional love. This angel aids in mending relationships, influencing kindness and emotional recovery. Invoked for mercy and harmony. Associated with universal love. Invocation: Meditation on forgiveness. Born under Haziel are compassionate healers. Offers forgiveness and divine mercy. Facilitates mercy. Favors mentally and emotionally resilient. Extends pardons to penitent wrongdoers. Loves and protects outcasts, vagrants, and vagabonds.", "psalm": "25:6", "sigil_desc": "Features a six-pointed star with the divine name Hazi repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Haziel formed by a single anti-clockwise ring of letters, including the suffix el added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 10, "name": "Aladiah", "zodiac": "Taurus", "element": "Earth", "attributes": "🔄🌟 Aladiah, bearer of second chances with healing ability, protects from negative influences and purifies spiritually by offering grace and renewal after errors. This angel supports recovery from illness and moral regeneration, influencing divine grace. Invoked for healing and protection. Associated with purity. Invocation: Psalms for redemption. Ideal for those seeking fresh starts. Aids in recovery from illness and personal transformation. Protection from negative influences, purification, and renewal. Helps in healing and spiritual cleansing.", "psalm": "33:22", "sigil_desc": "Features a six-pointed star with the divine name Alad repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Aladiah formed by a single anti-clockwise ring of letters, including the suffix iah added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 11, "name": "Lauviah", "zodiac": "Taurus", "element": "Earth", "attributes": "🧠🔮 Lauviah enhances intuition in earthly and spiritual realms, inspires revelation and intuitive wisdom by aiding prophetic dreams and higher understanding. This angel combats insomnia and anxiety, influencing fame through talents. Invoked for intuition. Associated with night visions. Invocation: Night meditations. Born under Lauviah are intuitive visionaries. Provides relief from anxiety and deepens spiritual wisdom. Angel of discipline, strong will, and determination. Helps with regulation and temperance. Reveals prophecies through dreams. Lover of music, poetry, fine literature. Ally to innovators.", "psalm": "18:46", "sigil_desc": "Features a six-pointed star with the divine name Lau repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Lauviah formed by a single anti-clockwise ring of letters, including the suffix iah added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 12, "name": "Hahaiah", "zodiac": "Taurus", "element": "Earth", "attributes": "❤️🛡️ Hahaiah teaches self-love and meditation, provides refuge and comfort in distress by protecting from adversity and revealing hidden truths. This angel influences discretion and wisdom. Invoked for shelter. Associated with inner peace. Invocation: Meditative prayers. Ideal for self-care seekers. Unlocks intuition and helps decipher dreams. Safeguards against adversity. Governs dream world, protects during dream work, lucid dreaming, or astral travel. Guardian of astral realm. Witty, enjoys riddles, protects mortals in astral realm.", "psalm": "10:1", "sigil_desc": "Features a six-pointed star with the divine name Haha repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Hahaiah formed by a single anti-clockwise ring of letters, including the suffix iah added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 13, "name": "Iezalel", "zodiac": "Gemini", "element": "Air (Metal)", "attributes": "👫🤝 Iezalel brings reconciliation in relationships, fosters loyalty and fidelity in friendships by repairing broken bonds and enhancing memory. This angel influences unity and harmony. Invoked for loyalty. Associated with partnerships. Invocation: Relationship rituals. Born under Iezalel are loyal companions. Strengthens friendships and promotes unity. Sociable and charismatic; teaches adaptability; endows social charisma and magnetism. Endows star quality. Facilitates successful marriages or improves conjugal relations.", "psalm": "98:4", "sigil_desc": "Features a six-pointed star with the divine name Iezal repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Iezalel formed by a single anti-clockwise ring of letters, including the suffix el added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 14, "name": "Mebahel", "zodiac": "Gemini", "element": "Air (Metal)", "attributes": "⚖️🗽 Mebahel, protector of truth, justice, freedom, and commitment, aids in liberation from oppression by defending the innocent and abolishing slavery. This angel influences legal victories. Invoked for justice. Associated with truth. Invocation: Psalms for freedom. Ideal for activists. Brings truth, justice, and fairness. Protects against exploitation. Champion of truth, liberty, and justice. Guardian over prisoners and oppressed. Lover of legal studies, affinity for courts, judges, attorneys.", "psalm": "9:9", "sigil_desc": "Features a six-pointed star with the divine name Mebah repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Mebahel formed by a single anti-clockwise ring of letters, including the suffix el added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 15, "name": "Hariel", "zodiac": "Gemini", "element": "Air (Metal)", "attributes": "🧹🌱 Hariel helps rid addictions and dependencies, promotes purification and spiritual growth by aiding scientific discoveries and religious sentiments. This angel influences purity and faith. Invoked for cleansing. Associated with renewal. Invocation: Purification rituals. Born under Hariel are pure innovators. Inspires artistic creativity and spiritual purity. Pious angel of moral purity governing arts and sciences; helps discover truths; endows creativity and inspiration; promotes human knowledge of sciences.", "psalm": "128:4", "sigil_desc": "Features a six-pointed star with the divine name Hari repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Hariel formed by a single anti-clockwise ring of letters, including the suffix el added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 16, "name": "Hekamiah", "zodiac": "Gemini", "element": "Air (Metal)", "attributes": "👑🤝 Hakamiah teaches loyalty according to divine principles, guards against betrayal and fosters peace by crowning the deserving and protecting from traitors. This angel influences nobility and frankness. Invoked for loyalty. Associated with crown. Invocation: Loyalty oaths. Ideal for leaders. Encourages leadership and loyalty. Protector of leaders and pioneers. Guides with strength, courage, ensures victory. Sensitive, loyal nature.", "psalm": "88:1", "sigil_desc": "Features a six-pointed star with the divine name Hekam repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Hekamiah formed by a single anti-clockwise ring of letters, including the suffix iah added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 17, "name": "Lauviah", "zodiac": "Gemini", "element": "Air (Metal)", "attributes": "🏆💪 Lauviah, angel of victory and successful people, aids in overcoming challenges and manifesting desires by granting fame to artists and protection from storms. This angel influences triumph and sleep. Invoked for success. Associated with victory. Invocation: Victory chants. Born under Lauviah are winners. Offers protection and serenity during hardships. Wonderful. Angel of discipline, strong will, and determination. Helps with regulation and temperance. Reveals prophecies through dreams. Lover of music, poetry, fine literature. Ally to innovators.", "psalm": "8:9", "sigil_desc": "Features a six-pointed star with the divine name Lau repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Lauviah formed by a single anti-clockwise ring of letters, including the suffix iah added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 18, "name": "Caliel", "zodiac": "Gemini", "element": "Air (Metal)", "attributes": "⚖️👁️ Caliel helps understand good vs. evil, promotes justice and moral integrity by revealing truth in trials and confounding the guilty. This angel influences divine justice. Invoked for clarity. Associated with truth. Invocation: Justice prayers. Ideal for judges. Defends against injustice and false accusations. Allows discernment of truth in all things. Helps win legal cases. Assists in overcoming adversity.", "psalm": "35:24", "sigil_desc": "Features a six-pointed star with the divine name Cali repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Caliel formed by a single anti-clockwise ring of letters, including the suffix el added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 19, "name": "Leuviah", "zodiac": "Cancer", "element": "Water", "attributes": "🧠📜 Leuviah saves memories of past lives, enhances memory and learning abilities by granting intelligence and joviality. This angel influences forgiveness and patience. Invoked for memory. Associated with past. Invocation: Memory meditations. Born under Leuviah are wise rememberers. Strengthens memory and aids in emotional healing. Expansive intelligence, excellent memory, and fruitful imagination. Helps bear adversities with patience and acceptance.", "psalm": "40:1", "sigil_desc": "Features a six-pointed star with the divine name Leu repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Leuviah formed by a single anti-clockwise ring of letters, including the suffix iah added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 20, "name": "Pahaliah", "zodiac": "Cancer", "element": "Water", "attributes": "🔄🙏 Pahaliah helps rid old bad behaviors, aids spiritual growth and divine wisdom by discerning truth and promoting virtue. This angel influences theology and morality. Invoked for redemption. Associated with virtue. Invocation: Conversion rituals. Ideal for seekers of truth. Deepens faith and spiritual practices. Redeemer. Helps discover one's vocation, facilitates religious or spiritual calling. Victory over enemies. Dominion over morals.", "psalm": "119:108", "sigil_desc": "Features a six-pointed star with the divine name Pahal repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Pahaliah formed by a single anti-clockwise ring of letters, including the suffix iah added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 21, "name": "Nelchael", "zodiac": "Cancer", "element": "Water", "attributes": "📚🛡️ Nelchael, for those desiring to learn, helps with knowledge and dispelling ignorance by conquering calumniators and loving mathematics. This angel influences sciences and arts. Invoked for learning. Associated with knowledge. Invocation: Study psalms. Born under Nelchael are eager scholars. Protects against slander and boosts intellectual pursuits. Thirst for knowledge. Affinity for math and astronomy. Protects against calumny and spells.", "psalm": "31:14", "sigil_desc": "Features a six-pointed star with the divine name Nelch repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Nelchael formed by a single anti-clockwise ring of letters, including the suffix el added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 22, "name": "Yeiaiel", "zodiac": "Cancer", "element": "Water", "attributes": "📏⭐ Yeiaiel brings sense of order and discipline, aids fame, fortune, and accomplishment by protecting commerce and travel. This angel influences diplomacy and voyages. Invoked for order. Associated with fortune. Invocation: Travel prayers. Ideal for entrepreneurs. Governs fame, diplomacy, commerce, and travel. It aids in resolving conflicts, protecting against adversity, and fostering clear communication.", "psalm": "121:5", "sigil_desc": "resembling intertwined waves and a crown; Features a six-pointed star with the divine name Ieiai repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Ieiaiel formed by a single anti-clockwise ring of letters, including the suffix el added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 23, "name": "Melahel", "zodiac": "Cancer", "element": "Water", "attributes": "🌿👩‍⚕️ Melahel heals and protects healers, promotes vitality and protection during travel by curing diseases and aiding in plant knowledge. This angel influences nature and courage. Invoked for healing. Associated with herbs. Invocation: Healing rituals. Born under Melahel are natural healers. Heals physical ailments and supports environmental protection. Healing plants and herbs. Protection in travel. Bold warrior spirit.", "psalm": "121:8", "sigil_desc": "Features a six-pointed star with the divine name Melah repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Melahel formed by a single anti-clockwise ring of letters, including the suffix el added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 24, "name": "Haheuiah", "zodiac": "Cancer", "element": "Water", "attributes": "🗣️🔍 Hahuiah grants sincerity and truth, helps discernment and defending integrity by protecting exiles and granting grace. This angel influences amnesty. Invoked for truth. Associated with sincerity. Invocation: Truth psalms. Ideal for honest souls. Protects travelers and guides those who feel lost. Protection for exiles. Mercy for criminals seeking sincere redemption. Guards against thieves and murderers.", "psalm": "33:18", "sigil_desc": "Features a six-pointed star with the divine name Haheu repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Haheuiah formed by a single anti-clockwise ring of letters, including the suffix iah added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 25, "name": "Nith-Haiah", "zodiac": "Leo", "element": "Fire", "attributes": "📖✨ Nithaiah provides wisdom and spiritual understanding, aids access to hidden truths and mysticism by revealing mysteries through dreams. This angel influences occult sciences. Invoked for wisdom. Associated with magic. Invocation: Dream rituals. Born under Nithaiah are mystics. Offers access to esoteric knowledge and mystical insight. Dominion over occult sciences and magick. Reveals hidden mysteries to the wise. Peaceful, reserved nature.", "psalm": "9:1", "sigil_desc": "Features a six-pointed star with the divine name Nith repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Nith-Haiah formed by a single anti-clockwise ring of letters, including the suffix iah added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 26, "name": "Haaiah", "zodiac": "Leo", "element": "Fire", "attributes": "🤝🕊️ Haaiah promotes diplomacy and conflict resolution, fosters peace and cooperation by aiding ambassadors and protecting secrets. This angel influences political science. Invoked for peace. Associated with discretion. Invocation: Diplomacy prayers. Ideal for negotiators. Encourages diplomacy and helps achieve success in negotiations. Angel of political science and ambition. Wins favors from influential people. Loves truth and peace.", "psalm": "119:145", "sigil_desc": "Features a six-pointed star with the divine name Haa repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Haaiah formed by a single anti-clockwise ring of letters, including the suffix iah added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 27, "name": "Ierathel", "zodiac": "Leo", "element": "Fire", "attributes": "🔄🌟 Yeratel aids transformation and positive change, supports personal growth by confounding enemies and propagating light. This angel influences civilization and liberty. Invoked for change. Associated with light. Invocation: Transformation rites. Born under Yeratel are reformers. Inspires confidence and positivity in difficult times. Protector against slander and unjust attacks. Confounds enemies. Propagates enlightenment.", "psalm": "140:1", "sigil_desc": "Features a six-pointed star with the divine name Ierat repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Ierathel formed by a single anti-clockwise ring of letters, including the suffix el added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 28, "name": "Seheiah", "zodiac": "Leo", "element": "Fire", "attributes": "🛡️🩹 Seheiah offers protection and longevity, wards off illness and adversity by foreseeing dangers and aiding recovery. This angel influences health and prudence. Invoked for protection. Associated with longevity. Invocation: Health psalms. Ideal for guardians of health. Provides healing and protection from accidents. Protection against catastrophes, accidents, and illness. Prudence and foresight. Long life.", "psalm": "71:12", "sigil_desc": "Features a six-pointed star with the divine name Sehei repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Seheiah formed by a single anti-clockwise ring of letters, including the suffix iah added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 29, "name": "Reyel", "zodiac": "Leo", "element": "Fire", "attributes": "📣🌟 Reiyel provides divine inspiration and guidance, aids enlightenment by liberating from enemies and promoting religious sentiment. This angel influences meditation. Invoked for inspiration. Associated with liberation. Invocation: Enlightenment meditations. Born under Reiyel are inspired leaders. Strengthens connection to the divine and moral integrity. Liberation from enemies. Protects against false prophets and religious fanaticism. Love of truth.", "psalm": "54:4", "sigil_desc": "Features a six-pointed star with the divine name Rey repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Reyel formed by a single anti-clockwise ring of letters, including the suffix el added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 30, "name": "Omael", "zodiac": "Leo", "element": "Fire", "attributes": "⏳🌱 Omael promotes patience and fertility, nurtures growth and abundance by multiplying species and confounding despair. This angel influences chemistry and physicians. Invoked for fertility. Associated with multiplication. Invocation: Growth rituals. Ideal for creators. Brings joy, optimism, and fertility. Multiplies joy and fertility. Patience in despair. Patron of chemists and physicians.", "psalm": "71:5", "sigil_desc": "Features a six-pointed star with the divine name Oma repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Omael formed by a single anti-clockwise ring of letters, including the suffix el added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 31, "name": "Lecabel", "zodiac": "Virgo", "element": "Earth", "attributes": "🧠🎨 Lecabel enhances intelligence and creativity, aids problem-solving and innovation by inspiring artists and administrators. This angel influences vegetation and astronomy. Invoked for ideas. Associated with talent. Invocation: Creative prayers. Born under Lecabel are innovators. Enhances problem-solving skills and agricultural success. Talent in geometry and astronomy. Solves difficult problems. Loves lucidity.", "psalm": "71:16", "sigil_desc": "Features a six-pointed star with the divine name Lecab repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Lecabel formed by a single anti-clockwise ring of letters, including the suffix el added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 32, "name": "Vasariah", "zodiac": "Virgo", "element": "Earth", "attributes": "⚖️❤️ Vasariah supports justice and forgiveness, promotes balance and harmony by aiding judges and eloquent speakers. This angel influences memory and generosity. Invoked for clemency. Associated with justice. Invocation: Forgiveness psalms. Ideal for mediators. Supports forgiveness and intellectual development. Clemency and mercy. Good memory, eloquent speech. Helps in legal matters.", "psalm": "33:4", "sigil_desc": "Features a six-pointed star with the divine name Vasar repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Vasariah formed by a single anti-clockwise ring of letters, including the suffix iah added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 33, "name": "Yehuiah", "zodiac": "Virgo", "element": "Earth", "attributes": "🙏👑 Yehuiah aids obedience and loyalty, helps discern divine will by protecting princes and confounding conspiracies. This angel influences subordination. Invoked for loyalty. Associated with hierarchy. Invocation: Obedience rituals. Born under Yehuiah are devoted followers. Encourages loyalty and exposes hidden enemies. Subordination to superiors. Reveals traitors. Protects princes.", "psalm": "131:3", "sigil_desc": "Features a six-pointed star with the divine name Yehui repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Yehuiah formed by a single anti-clockwise ring of letters, including the suffix iah added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 34, "name": "Lehahiah", "zodiac": "Virgo", "element": "Earth", "attributes": "📏🏗️ Lehahiah promotes order and stability, helps with focus and long-term goals by calming wrath and gaining favor from superiors. This angel influences faithful service. Invoked for order. Associated with peace. Invocation: Stability prayers. Ideal for organizers. Inspires obedience and promotes peaceful coexistence. Obedient nature. Calms anger. Faithful servant.", "psalm": "131:3", "sigil_desc": "Features a six-pointed star with the divine name Leha repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Lehahiah formed by a single anti-clockwise ring of letters, including the suffix iah added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 35, "name": "Chavakiah", "zodiac": "Virgo", "element": "Earth", "attributes": "🤝💔 Chavakiah aids reconciliation and healing relationships by maintaining harmony in families and aiding inheritances. This angel influences amicable divisions. Invoked for harmony. Associated with family. Invocation: Reconciliation rites. Born under Chavakiah are peacemakers. Reconciles conflicts and strengthens familial bonds. Reconciliation. Maintains peace in families. Dominion over estates and inheritance.", "psalm": "116:1", "sigil_desc": "Features a six-pointed star with the divine name Chavak repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Chavakiah formed by a single anti-clockwise ring of letters, including the suffix iah added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 36, "name": "Menadel", "zodiac": "Virgo", "element": "Earth", "attributes": "💼📈 Menadel supports work and productivity, helps find purpose and career advancement by preserving employment and aiding exiles. This angel influences inner conviction. Invoked for work. Associated with labor. Invocation: Career psalms. Ideal for professionals. Aids in finding lost objects and regaining employment. Liberation from bad habits. Protects against calumny. Maintains employment.", "psalm": "26:8", "sigil_desc": "Features a six-pointed star with the divine name Menad repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Menadel formed by a single anti-clockwise ring of letters, including the suffix el added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 37, "name": "Aniel", "zodiac": "Libra", "element": "Air (Metal)", "attributes": "💥🧠 Aniel aids spiritual breakthroughs and inner strength, overcomes challenges by inspiring scientists and breaking old habits. This angel influences meditation. Invoked for breakthroughs. Associated with virtue. Invocation: Strength meditations. Born under Aniel are breakthrough achievers. Promotes spiritual ascension and courage. Victory over obstacles. Breaks vicious cycles. Inspires through sciences.", "psalm": "80:15", "sigil_desc": "Features a six-pointed star with the divine name Ani repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Aniel formed by a single anti-clockwise ring of letters, including the suffix el added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 38, "name": "Haamiah", "zodiac": "Libra", "element": "Air (Metal)", "attributes": "🕯️🙏 Haamiah supports ritual and spiritual practice, connects with divine energies by preparing for ceremonies and protecting from error. This angel influences religious cults. Invoked for rituals. Associated with truth. Invocation: Ceremony prayers. Ideal for practitioners. Protects against negativity and enhances ritual practices. Prepares for rituals. Protects against lightning and violence. Exorcism.", "psalm": "91:9", "sigil_desc": "Features a six-pointed star with the divine name Haam repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Haamiah formed by a single anti-clockwise ring of letters, including the suffix iah added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 39, "name": "Rehael", "zodiac": "Libra", "element": "Air (Metal)", "attributes": "🩹👨‍👩‍👧 Rehael promotes healing and familial love, fosters harmony in family by curing diseases and inspiring filial respect. This angel influences health and longevity. Invoked for healing. Associated with paternity. Invocation: Family rituals. Born under Rehael are healers. Encourages compassion and emotional healing. Filial submission. Cures mental illnesses. Paternal love.", "psalm": "30:10", "sigil_desc": "Features a six-pointed star with the divine name Reha repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Rehael formed by a single anti-clockwise ring of letters, including the suffix el added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 40, "name": "Ieiazel", "zodiac": "Libra", "element": "Air (Metal)", "attributes": "🗽🔓 Ieiazel aids liberation from oppression, breaks negative patterns by consoling prisoners and aiding writers. This angel influences printing and libraries. Invoked for liberation. Associated with comfort. Invocation: Freedom psalms. Ideal for liberators. Offers comfort during grief and aids in creative pursuits. Liberation from oppression. Consoles prisoners. Influences printing and books.", "psalm": "88:14", "sigil_desc": "Features a six-pointed star with the divine name Ieiaz repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Ieiazel formed by a single anti-clockwise ring of letters, including the suffix el added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 41, "name": "Hahahel", "zodiac": "Libra", "element": "Air (Metal)", "attributes": "🙏🔥 Hahahel inspires faith and devotion, supports spiritual service by confounding enemies of religion and aiding missionaries. This angel influences clergy. Invoked for faith. Associated with virtue. Invocation: Devotion prayers. Born under Hahahel are faithful servants. Inspires faith and moral virtue. Vocation for priesthood. Victory over enemies. Great generosity.", "psalm": "120:2", "sigil_desc": "Features a six-pointed star with the divine name Haha repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Hahahel formed by a single anti-clockwise ring of letters, including the suffix el added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 42, "name": "Mikael", "zodiac": "Libra", "element": "Air (Metal)", "attributes": "👑📜 Mikael aids in politics and leadership, maintains order and collective goals by overseeing voyages and inspiring diplomats. This angel influences teachers of politics. Invoked for order. Associated with vision. Invocation: Leadership rituals. Ideal for leaders. Guides political leaders and promotes harmony. Political authority. Surveillance of empires. Influences voyages.", "psalm": "121:7", "sigil_desc": "Features a six-pointed star with the divine name Mika repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Mikael formed by a single anti-clockwise ring of letters, including the suffix el added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 43, "name": "Veuliah", "zodiac": "Scorpio", "element": "Water", "attributes": "💰🏆 Veualiah brings prosperity and success in endeavors, manifests wealth by destroying enemies and exalting through victory. This angel influences peace and commerce. Invoked for prosperity. Associated with military. Invocation: Success psalms. Born under Veualiah are prosperous warriors. Brings prosperity and victory in endeavors. Prosperity. Confounds the wicked. Dominion over great captains.", "psalm": "88:13", "sigil_desc": "Features a six-pointed star with the divine name Veuli repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Veuliah formed by a single anti-clockwise ring of letters, including the suffix iah added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 44, "name": "Yelahiah", "zodiac": "Scorpio", "element": "Water", "attributes": "💪🛡️ Yelahiah provides valor and courage, offers protection in conflicts by ensuring success in useful enterprises and protecting magistrates. This angel influences warriors. Invoked for courage. Associated with virtue. Invocation: Valor prayers. Ideal for brave souls. Provides protection during travel and legal battles. Success in arms. Loyalty of soldiers. Protects against sedition.", "psalm": "119:108", "sigil_desc": "Features a six-pointed star with the divine name Yelah repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Yelahiah formed by a single anti-clockwise ring of letters, including the suffix iah added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 45, "name": "Sealiah", "zodiac": "Scorpio", "element": "Water", "attributes": "🔥💥 Sealiah motivates enthusiasm and awakening passion, overcomes inertia by confounding the proud and restoring health. This angel influences vegetation and fire. Invoked for motivation. Associated with movement. Invocation: Enthusiasm rituals. Born under Sealiah are passionate movers. Motivates and energizes individuals. Confounds the wicked. Raises up the oppressed. Dominion over vegetation.", "psalm": "94:18", "sigil_desc": "Features a six-pointed star with the divine name Seali repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Sealiah formed by a single anti-clockwise ring of letters, including the suffix iah added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 46, "name": "Ariel", "zodiac": "Scorpio", "element": "Water", "attributes": "🔮📖 Ariel enhances revelation and psychic abilities, uncovers hidden truths by aiding discoveries and perceptive dreams. This angel influences nocturnal visions. Invoked for revelation. Associated with perception. Invocation: Dream meditations. Ideal for psychics. Reveals hidden truths, treasures, and insights through dreams or intuition. It supports perception, discovery, and spiritual revelations.", "psalm": "145:9", "sigil_desc": "a key unlocking a door amid swirling mists; Features a six-pointed star with the divine name Ari repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Ariel formed by a single anti-clockwise ring of letters, including the suffix el added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 47, "name": "Asaliah", "zodiac": "Scorpio", "element": "Water", "attributes": "🧘‍♂️🔍 Asaliah promotes contemplation and divine understanding, provides clarity by elevating souls to see God's works. This angel influences physics and truth. Invoked for contemplation. Associated with elevation. Invocation: Contemplative prayers. Born under Asaliah are contemplative sages. Enhances contemplation and spiritual insight. Contemplation of divine. Elevates the soul. Discovers hidden secrets.", "psalm": "105:1", "sigil_desc": "Features a six-pointed star with the divine name Asal repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Asaliah formed by a single anti-clockwise ring of letters, including the suffix iah added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 48, "name": "Mihael", "zodiac": "Scorpio", "element": "Water", "attributes": "🌹👫 Mihael supports fertility and marital harmony, fosters loving relationships by preserving peace and union between spouses. This angel influences fidelity. Invoked for harmony. Associated with generation. Invocation: Love rituals. Ideal for couples. Promotes harmony in relationships and fertility. Unity between spouses. Peace and marital harmony. Fidelity.", "psalm": "98:2", "sigil_desc": "Features a six-pointed star with the divine name Miha repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Mihael formed by a single anti-clockwise ring of letters, including the suffix el added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 49, "name": "Vehuel", "zodiac": "Sagittarius", "element": "Fire", "attributes": "🌟🤲 Vehuel inspires elevation and generosity, promotes noble actions by exalting toward greatness and confounding flatterers. This angel influences sensitivity. Invoked for elevation. Associated with greatness. Invocation: Generosity psalms. Born under Vehuel are noble givers. Elevates the soul and encourages generosity. Sublime and exalted. Generosity. Sensitivity to higher realms.", "psalm": "145:3", "sigil_desc": "Features a six-pointed star with the divine name Vehu repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Vehuel formed by a single anti-clockwise ring of letters, including the suffix el added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 50, "name": "Daniel", "zodiac": "Sagittarius", "element": "Fire", "attributes": "🗣️⚖️ Daniel aids eloquence and decision-making, promotes mercy and wise judgment by consoling in adversity and influencing lawyers. This angel influences sympathy. Invoked for eloquence. Associated with mercy. Invocation: Decision prayers. Ideal for speakers. Offers mercy and aids in decision-making. Eloquence. Influences judges. Inspires decisions favoring innocents.", "psalm": "145:8", "sigil_desc": "Features a six-pointed star with the divine name Dani repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Daniel formed by a single anti-clockwise ring of letters, including the suffix el added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 51, "name": "Hahasiah", "zodiac": "Sagittarius", "element": "Fire", "attributes": "🩺🔬 Hahasiah promotes healing and medicine, supports physical and alchemical knowledge by revealing secrets of nature and elevating souls. This angel influences chemistry. Invoked for healing. Associated with stone of wise. Invocation: Healing rituals. Born under Hahasiah are healers and alchemists. Provides healing and alchemical knowledge. Universal medicine. Cures melancholy. Reveals secrets of nature.", "psalm": "104:31", "sigil_desc": "Features a six-pointed star with the divine name Hahas repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Hahasiah formed by a single anti-clockwise ring of letters, including the suffix iah added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 52, "name": "Imamiah", "zodiac": "Sagittarius", "element": "Fire", "attributes": "🔄❤️ Imamiah aids expiation and forgiveness, encourages self-reflection and redemption by destroying enemies and humbling the proud. This angel influences vigor. Invoked for forgiveness. Associated with journeys. Invocation: Redemption psalms. Ideal for redeemers. Protects against errors and promotes humility. Destroys enemies. Exalts the humiliated. Vigorous work ethic.", "psalm": "7:17", "sigil_desc": "Features a six-pointed star with the divine name Imam repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Imamiah formed by a single anti-clockwise ring of letters, including the suffix iah added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 53, "name": "Nanael", "zodiac": "Sagittarius", "element": "Fire", "attributes": "🧘‍♀️📚 Nanael supports spiritual communication and meditation, aids connection to higher knowledge by inspiring high sciences and influencing ecclesiastics. This angel influences abstraction. Invoked for communication. Associated with solitude. Invocation: Meditation rituals. Born under Nanael are spiritual scholars. Supports spiritual communication and meditation. Spiritual communication. Inspires meditation on divine. Teachers and men of law.", "psalm": "119:75", "sigil_desc": "Features a six-pointed star with the divine name Nana repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Nanael formed by a single anti-clockwise ring of letters, including the suffix el added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 54, "name": "Nithael", "zodiac": "Sagittarius", "element": "Fire", "attributes": "🛡️👑 Nithael provides stability and legitimacy, helps maintain health and positions by preserving kings and empires. This angel influences renown. Invoked for stability. Associated with beauty. Invocation: Stability prayers. Ideal for rulers. Brings stability and longevity. Eternal youth. Legitimacy and stability to empires. Mercy to subjects.", "psalm": "103:19", "sigil_desc": "Features a six-pointed star with the divine name Nitha repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Nithael formed by a single anti-clockwise ring of letters, including the suffix el added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 55, "name": "Mebahiah", "zodiac": "Capricorn", "element": "Earth", "attributes": "🧠🕊️ Mebahiah aids intellectual lucidity and moral integrity by contemplating divine ideas and inspiring religion. This angel influences morality. Invoked for lucidity. Associated with consolation. Invocation: Moral rituals. Born under Mebahiah are moral thinkers. Enhances intellectual clarity and moral integrity. Lucidity and consolation. Inspires religious sentiment. Virtuous living.", "psalm": "102:12", "sigil_desc": "Features a six-pointed star with the divine name Mebah repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Mebahiah formed by a single anti-clockwise ring of letters, including the suffix iah added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 56, "name": "Poyel", "zodiac": "Capricorn", "element": "Earth", "attributes": "🍀🤗 Poyel brings fortune and support with modesty and humility by granting health, wealth, and philosophical talents. This angel influences fame. Invoked for fortune. Associated with moderation. Invocation: Humility psalms. Ideal for modest achievers. Associated with modesty, moderation, a good sense of humor, and success achieved through talent and good conduct. Linked to fortune, fame, and the fulfillment of wishes. Influences individuals to be humble, optimistic, and guided towards divine success. Seen as the quiet force behind achieving goals, realizing dreams, and receiving answered prayers.", "psalm": "145:14", "sigil_desc": "Features a six-pointed star with the divine name Poy repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Poyel formed by a single anti-clockwise ring of letters, including the suffix el added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 57, "name": "Nemamiah", "zodiac": "Capricorn", "element": "Earth", "attributes": "🔍💼 Nemamiah reveals deep personal problems, provides discernment, leadership, and prosperity by aiding generals and freeing prisoners. This angel influences prosperity. Invoked for discernment. Associated with labor. Invocation: Leadership prayers. Born under Nemamiah are discerning leaders. Aids in prosperity and military success. Prosperity. Liberation of prisoners. Brave in battle. Loves military careers.", "psalm": "115:11", "sigil_desc": "Features a six-pointed star with the divine name Nemam repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Nemamiah formed by a single anti-clockwise ring of letters, including the suffix iah added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 58, "name": "Yeialel", "zodiac": "Capricorn", "element": "Earth", "attributes": "🔮🧠 Yeialel develops psychic abilities like clairvoyance, combats sorrow for mental clarity by consoling and healing eye diseases. This angel influences commerce. Invoked for clairvoyance. Associated with fortitude. Invocation: Psychic rituals. Ideal for seers. Heals mental ailments and promotes clarity. Combats sorrow. Patron of ironwork and blacksmiths. Mental agility.", "psalm": "6:3", "sigil_desc": "Features a six-pointed star with the divine name Yeial repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Yeialel formed by a single anti-clockwise ring of letters, including the suffix el added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 59, "name": "Harahel", "zodiac": "Capricorn", "element": "Earth", "attributes": "🌟💭 Harahel helps make dreams come true with positive energy, aiding intellectual pursuits and protecting from sterility. This angel influences treasures. Invoked for fertility. Associated with children. Invocation: Dream fulfillment prayers. Born under Harahel are fertile minds. Protects children and aids in financial matters. Intellectual curiosity. Fertility. Protects treasuries and archives.", "psalm": "113:9", "sigil_desc": "Features a six-pointed star with the divine name Harah repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Harahel formed by a single anti-clockwise ring of letters, including the suffix el added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 60, "name": "Mitzrael", "zodiac": "Capricorn", "element": "Earth", "attributes": "🔧⚖️ Mitzrael corrects mistakes, guides to understand authority by curing mental ills and inspiring loyalty. This angel influences virtue. Invoked for correction. Associated with reparation. Invocation: Authority psalms. Ideal for teachers. Heals illnesses and promotes loyalty. Reparation and virtue. Liberation from persecutors. Inspires loyalty.", "psalm": "145:17", "sigil_desc": "Features a six-pointed star with the divine name Mitzr repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Mitzrael formed by a single anti-clockwise ring of letters, including the suffix el added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 61, "name": "Umabel", "zodiac": "Aquarius", "element": "Air (Metal)", "attributes": "🔍🌍 Umabel provides deep awareness of life, concentration by aiding friendships and affinity with astronomy. This angel influences physicists. Invoked for awareness. Associated with analogy. Invocation: Friendship rituals. Born under Umabel are aware friends. Strengthens friendships and affinity. Affinity for astronomy and physics. Obtains friendships. Pleasurable travel.", "psalm": "113:2", "sigil_desc": "Features a six-pointed star with the divine name Umab repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Umabel formed by a single anti-clockwise ring of letters, including the suffix el added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 62, "name": "Iahhel", "zodiac": "Aquarius", "element": "Air (Metal)", "attributes": "☀️🧘 Iahhel boosts positive thoughts, teaches enjoyment of solitude and tranquility by acquiring wisdom and aiding retirement. This angel influences philosophers. Invoked for positivity. Associated with knowledge. Invocation: Solitude meditations. Ideal for philosophers. Offers wisdom and enlightenment. Supreme knowledge. Modest living. Marital tranquility. Philosopher's stone.", "psalm": "119:159", "sigil_desc": "Features a six-pointed star with the divine name Iahh repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Iahhel formed by a single anti-clockwise ring of letters, including the suffix el added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 63, "name": "Anauel", "zodiac": "Aquarius", "element": "Air (Metal)", "attributes": "📞🤝 Anauel ensures successful communication and relationships by protecting commerce and uniting spirits. This angel influences cashiers. Invoked for communication. Associated with unity. Invocation: Relationship prayers. Born under Anauel are communicators. Protects commerce and promotes unity. Unity of all things. Protects against accidents. Inspires bankers and merchants.", "psalm": "37:4", "sigil_desc": "Features a six-pointed star with the divine name Anau repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Anauel formed by a single anti-clockwise ring of letters, including the suffix el added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 64, "name": "Mehiel", "zodiac": "Aquarius", "element": "Air (Metal)", "attributes": "🧠🛡️ Mehiel favors imagination, intelligence, protects against dark energies by inspiring writers and aiding against rabies. This angel influences printing. Invoked for imagination. Associated with literature. Invocation: Creative psalms. Ideal for creators. Inspires writers and protects against negativity. Vivification. Protects against rabies and ferocious animals. Inspires writers.", "psalm": "33:18", "sigil_desc": "Features a six-pointed star with the divine name Mehi repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Mehiel formed by a single anti-clockwise ring of letters, including the suffix el added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 65, "name": "Damabiah", "zodiac": "Aquarius", "element": "Air (Metal)", "attributes": "❤️🔄 Damabiah gives unconditional love, supports transformation by aiding naval enterprises and protecting from shipwrecks. This angel influences seas. Invoked for love. Associated with wisdom. Invocation: Love rituals. Born under Damabiah are loving transformers. Offers wisdom and protection at sea. Fountain of wisdom. Success in naval enterprises. Protects against sorcery.", "psalm": "90:13", "sigil_desc": "Features a six-pointed star with the divine name Dama repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Damabiah formed by a single anti-clockwise ring of letters, including the suffix iah added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 66, "name": "Manakel", "zodiac": "Aquarius", "element": "Air (Metal)", "attributes": "😨🔍 Manakel eliminates fears through understanding, aids emotional stability by calming nightmares and aiding vegetation. This angel influences sleep. Invoked for stability. Associated with goodness. Invocation: Fear-banishing prayers. Ideal for peaceful sleepers. Heals sleep disorders and promotes peace. Goodness. Calms anger. Dominion over vegetation. Cures sleep disorders.", "psalm": "38:21", "sigil_desc": "Features a six-pointed star with the divine name Mana repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Manakel formed by a single anti-clockwise ring of letters, including the suffix el added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 67, "name": "Eyael", "zodiac": "Pisces", "element": "Water", "attributes": "🧭💪 Eiael guides good decisions, supports when all seems lost, enhances learning by consoling in adversity and aiding occult sciences. This angel influences truth. Invoked for guidance. Associated with commerce. Invocation: Decision rituals. Born under Eiael are resilient learners. Transforms sorrow into joy and aids in studies. Consolation in adversity. Love of solitude. Wisdom in philosophy.", "psalm": "37:4", "sigil_desc": "Features a six-pointed star with the divine name Eya repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Eyael formed by a single anti-clockwise ring of letters, including the suffix el added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 68, "name": "Habuhiah", "zodiac": "Pisces", "element": "Water", "attributes": "🩹🌿 Habuhiah patterns for medical and spiritual treatments, promotes vitality and health by curing diseases and aiding agriculture. This angel influences fertility. Invoked for health. Associated with harvest. Invocation: Healing psalms. Ideal for healers. Heals diseases and supports agriculture. Healing. Fertility of earth. Successful harvests.", "psalm": "106:1", "sigil_desc": "Features a six-pointed star with the divine name Habu repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Habuhiah formed by a single anti-clockwise ring of letters, including the suffix iah added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 69, "name": "Rochel", "zodiac": "Pisces", "element": "Water", "attributes": "⚖️🏆 Rochel gives what is deserved, symbolizes justice and equity by restoring lost goods and aiding fame. This angel influences renown. Invoked for justice. Associated with rights. Invocation: Equity prayers. Born under Rochel are just victors. Helps find lost objects and promotes justice. Restitution. Finds lost objects. Influences renown through talent.", "psalm": "16:5", "sigil_desc": "Features a six-pointed star with the divine name Roch repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Rochel formed by a single anti-clockwise ring of letters, including the suffix el added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 70, "name": "Yabamiah", "zodiac": "Pisces", "element": "Water", "attributes": "🌟🩹 Jabamiah delivers healing energy, regenerates and restores harmony by governing phenomena and aiding philosophy. This angel influences creation. Invoked for healing. Associated with alchemy. Invocation: Regeneration rituals. Ideal for regenerators. Facilitates creation, regeneration, and alchemical transformation. It inspires philosophical understanding, harmony with nature, and the ability to manifest ideas into reality.", "psalm": "Genesis 1:1", "sigil_desc": "a phoenix rising from water; Features a six-pointed star with the divine name Yabam repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Yabamiah formed by a single anti-clockwise ring of letters, including the suffix iah added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 71, "name": "Haiaiel", "zodiac": "Pisces", "element": "Water", "attributes": "🛡️⚖️ Haiaiel provides divine protection, helps make just decisions by confounding traitors and delivering the oppressed. This angel influences courage. Invoked for protection. Associated with weapons. Invocation: Protection psalms. Born under Haiaiel are protected deciders. Provides courage and protection against evil. Discernment. Victory over traitors. Protects against conspiracies.", "psalm": "109:30", "sigil_desc": "Features a six-pointed star with the divine name Haiai repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Haiaiel formed by a single anti-clockwise ring of letters, including the suffix el added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 72, "name": "Mumiah", "zodiac": "Pisces", "element": "Water", "attributes": "🔄⚡ Mumiah helps complete tasks, gives energy for new beginnings, revitalizes by bringing success to experiments and aiding medicine. This angel influences chemistry. Invoked for completion. Associated with disclosure. Invocation: Completion rituals. Ideal for finishers. Brings completion and success in endeavors. Brings undertakings to successful conclusion. Longevity and success in medicine.", "psalm": "116:7", "sigil_desc": "Features a six-pointed star with the divine name Mumi repeated three times—twice anti-clockwise around the outside of the star and once in the center, written from right to left. Also a pentagram with the Angel's name Mumiah formed by a single anti-clockwise ring of letters, including the suffix iah added to the Name of God. Includes a central pentagon space for desires, surrounded by patterns of light and dark texture for Empowered Angel Magick."},
    {"number": 73, "name": "Gabriel", "zodiac": "Transitional - Water signs (Cancer, Scorpio, Pisces)", "element": "Water", "attributes": "Encourages intuition, flexibility, and freedom from fears. Tied to the bladder and kidney meridians; brings fertility, wisdom, and spiritual information. Imbalance may result in fear control. Leader angel for Water element angels. 📜", "psalm": "91:11", "sigil_desc": "Often depicted with a lily or moon, representing intuition and flexibility; a complex symbol with Hebrew letters for invocation of divinity and intuition. ✒️"},
    {"number": 74, "name": "Nathaniel", "zodiac": "Transitional - Aether/Wood related signs", "element": "Aether (Wood)", "attributes": "Represents new beginnings, growth, and higher vibrations. Tied to the gall-bladder and liver meridians; aids in expanding consciousness and understanding limitless potential. Imbalance may cause complaining. Leader angel for Aether element angels. 📜", "psalm": "145:1-2", "sigil_desc": "Depicted with symbols of growth like a tree or rising sun, representing new beginnings and fire energy. ✒️"},
    {"number": 75, "name": "Michael", "zodiac": "Transitional - Fire signs (Aries, Leo, Sagittarius)", "element": "Fire", "attributes": "Inspires divine love, heart-opening, and overcoming depression. Tied to the heart and small intestine meridians; promotes spreading light and recognizing soul duality. Imbalance may cause depression. Leader angel for Fire element angels. 📜", "psalm": "91:11", "sigil_desc": "Composed of seven distinct parts in a circle with a cross, Hebrew letters, often including a sword and shield for protection and strength. ✒️"},
    {"number": 76, "name": "Uriel", "zodiac": "Transitional - Earth signs (Taurus, Virgo, Capricorn)", "element": "Earth", "attributes": "Promotes balance, peace, and guidance from doubt. Tied to the stomach and spleen meridians; radiates light to show life's path and encourage serenity. Imbalance may cause anxiety. Leader angel for Earth element angels. 📜", "psalm": "91:11", "sigil_desc": "Featuring a lantern or mountain, symbolizing guidance, wisdom, enlightenment, and protection; green and gold circular seal with symbols. ✒️"},
    {"number": 77, "name": "Raphael", "zodiac": "Transitional - Air signs (Gemini, Libra, Aquarius)", "element": "Air (Metal)", "attributes": "Focuses on healing, wisdom, and interconnectedness. Tied to the lung and large intestine meridians; assists in studies, music, medicine, and repairing disharmony. Imbalance may lead to downfall. Leader angel for Air element angels. 📜", "psalm": "29:1", "sigil_desc": "Featuring healing symbols like a staff with serpent or wings, for knowledge, wisdom, healing, and protective powers. ✒️"}
]

# Special dates and their archangels
special_dates = [
    (1, 5, 76),  # Jan 5, Uriel (Earth/Spring)
    (3, 19, 75),  # Mar 19, Michael (Fire/Summer)
    (5, 31, 73),  # May 31, Gabriel (Water/Wet)
    (8, 12, 74),  # Aug 12, Nathaniel (Aether/Autumn)
    (10, 24, 77)  # Oct 24, Raphael (Air/Winter)
]

# Periods after special dates for overseeing archangel
def get_period_archangel(birth_date):
    # Sort special dates by month and day
    sorted_special = sorted(special_dates, key=lambda x: (x[0], x[1]))
    for i, (m, d, arch_num) in enumerate(sorted_special):
        special_date = datetime(birth_date.year, m, d)
        if birth_date > special_date:
            # Check if before next special date
            next_i = (i + 1) % len(sorted_special)
            next_m, next_d, _ = sorted_special[next_i]
            next_date = datetime(birth_date.year if next_m >= m else birth_date.year + 1, next_m, next_d)
            if birth_date < next_date:
                return angels[arch_num - 1]
    # If after last, before first next year
    first_m, first_d, first_arch = sorted_special[0]
    first_date = datetime(birth_date.year + 1, first_m, first_d)
    if birth_date < first_date:
        last_arch = sorted_special[-1][2]
        return angels[last_arch - 1]
    return None

# Element to archangel mapping
element_to_archangel = {
    "Earth": angels[75],  # Uriel
    "Fire": angels[74],  # Michael
    "Water": angels[72],  # Gabriel
    "Aether (Wood)": angels[73],  # Nathaniel
    "Air (Metal)": angels[76]  # Raphael
}

def get_zodiac_sign(lon):
    lon = lon % 360
    zodiac_signs = [
        ("Aries", 0, 30),
        ("Taurus", 30, 60),
        ("Gemini", 60, 90),
        ("Cancer", 90, 120),
        ("Leo", 120, 150),
        ("Virgo", 150, 180),
        ("Libra", 180, 210),
        ("Scorpio", 210, 240),
        ("Sagittarius", 240, 270),
        ("Capricorn", 270, 300),
        ("Aquarius", 300, 330),
        ("Pisces", 330, 360),
    ]
    for sign, start, end in zodiac_signs:
        if start <= lon < end:
            return sign
    return "Pisces"

st.title("Guardian Angel Calculator")

st.markdown("""
### How it works
This app determines your guardian angel based on your birth date using Kabbalistic tradition. It calculates the sun's apparent ecliptic longitude at noon on your birth date and maps it to one of 72 angels (each governing 5 degrees of the zodiac circle, starting from the vernal equinox). This method provides accuracy for leap years and dates between 1900 and 2100, using astronomical formulas aligned with traditional references, including considerations for historical figures like Jesus (traditional birth December 25 corresponding to Poyel in approximate fixed ranges, but calculated precisely). The year is used to handle leap years correctly, and February 29 is valid only in leap years. Special birth dates (January 5, March 19, May 31, August 12, October 24) fill the calendar gaps for accuracy (360/72 angels cover 360 days, these 5 extra days link to archangels), allowing choice of any angel and a mission to guard humanity. For dates in specific periods, the corresponding archangel is the overseeing leader for that season, and the element's archangel is the leader for the angel's element and zodiac.
Updated seasonal analogy (custom, not standard TCM): Jan-Mar Earth/Spring Uriel, Mar-May Fire/Summer Michael, May-Aug Water/Wet Gabriel, Aug-Oct Aether/Autumn Nathaniel, Oct-Jan Air/Winter Raphael. The analogy is not standard in TCM (where Spring Wood, Summer Fire, Late Summer Earth, Autumn Metal, Winter Water), but updated as per user specification.
""")

# Input birth date
birth_date = st.date_input("Enter your birth date", min_value=datetime(1900, 1, 1), max_value=datetime(2100, 12, 31))

if st.button("Find My Guardian Angel"):
    if birth_date:
        year = birth_date.year
        month = birth_date.month
        day = birth_date.day

        if month == 2 and day == 29 and not calendar.isleap(year):
            st.error("February 29 is not valid for non-leap years. Please select a valid date.")
        else:
            # Calculate Julian Day at 0h UT
            y = year
            m = month
            d = day
            if m <= 2:
                y -= 1
                m += 12
            a = y // 100
            b = a // 4
            c = 2 - a + b
            e = int(365.25 * (y + 4716))
            f = int(30.6001 * (m + 1))
            jd = c + d + e + f - 1524.5

            # Add 0.5 for noon UT
            jd += 0.5

            # Calculate n
            n = jd - 2451545.0

            # Mean anomaly g in degrees
            g = (357.529 + 0.98560028 * n) % 360
            g_rad = math.radians(g)

            # Mean longitude L in degrees
            l = (280.459 + 0.98564736 * n) % 360

            # Apparent ecliptic longitude lambda in degrees
            lambda_deg = (l + 1.915 * math.sin(g_rad) + 0.020 * math.sin(2 * g_rad)) % 360

            # Calculate index (0 to 71 for regular angels)
            index = int(lambda_deg // 5)

            # Check if special date
            special = next((item for item in special_dates if item[0] == month and item[1] == day), None)
            if special:
                arch_num = special[2]
                angel = angels[arch_num - 1]
                zodiac = angel['zodiac']
                st.success(f"Your Guardian Archangel is **{angel['name']}** (Number {angel['number']}, Zodiac: {zodiac}, Element: {angel['element']}) (special gap date)")
            else:
                angel = angels[index]
                zodiac = get_zodiac_sign(lambda_deg)
                st.success(f"Your Guardian Angel is **{angel['name']}** (Number {angel['number']}, Zodiac: {zodiac}, Element: {angel['element']}) (based on ecliptic longitude {lambda_deg:.2f}°)")
            
            st.write(angel['attributes'])
            st.write(f"Psalm: {angel['psalm']}")
            st.write(f"Sigil Description: {angel['sigil_desc']}")

            # Get period overseeing archangel
            period_archangel = get_period_archangel(birth_date)
            if period_archangel:
                st.info(f"Overseeing Leader Archangel for this seasonal period: **{period_archangel['name']}** (Number {period_archangel['number']}, Element: {period_archangel['element']})")
                st.write(period_archangel['attributes'])
                st.write(f"Psalm: {period_archangel['psalm']}")
                st.write(f"Sigil Description: {period_archangel['sigil_desc']}")

            # Show element leader archangel
            element_leader = element_to_archangel.get(angel['element'])
            if element_leader and element_leader != period_archangel:
                st.info(f"Leader Archangel for {angel['element']} element and related zodiac signs: **{element_leader['name']}** (Number {element_leader['number']})")
                st.write(element_leader['attributes'])
                st.write(f"Psalm: {element_leader['psalm']}")
                st.write(f"Sigil Description: {element_leader['sigil_desc']}")
    else:
        st.warning("Please enter your birth date.")
